
version: 2

models:
  - name: test_dbt
    description: "A starter dbt model"
    columns:
      - name: Date
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: small1
    description: "Small data 1"
    columns:
      - name: seq
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: small2
    description: "Small data 2"
    columns:
      - name: seq
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
