
version: 2

models:
  - name: test_dbt
    description: "A starter dbt model"
    columns:
      - name: Date
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

